### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by arhmnsh** [vizabi/bubblechart#4]
hey guys!
Seems like you've separated bubblechart as separate component.
Is there any way I can use this now?

**Comment by angiehjort** [comment]
@arhmnsh yes, i'm now writing up instructions how. can you please tell me your use case? what do you want to do with it?

**Comment by arhmnsh** [comment]
I work for a telecom company. Trying to show data in this viz - http://vizabi.org/examples/bubble-chart.html

**Comment by angiehjort** [comment]
@arhmnsh just published! please check if this would help you http://vizabi.org/tutorials/

feel free to ask any questions and give your feedback!
